
spring.application.name=inventoryManagement
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

#my sql configuration

#spring.datasource.url=jdbc:mysql://localhost:3306/inventorydb
#spring.datasource.username=root
#spring.datasource.password=root

#spring.datasource.url=jdbc:mysql://localhost:3306/inventorydb
#spring.datasource.username=root


#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql=true

#jpa configuration
#spring.jpa.hibernate.ddl-auto=update


#razorpay
razorpay.key.id=rzp_test_AYfSh7nXRuJebv
razorpay.key.secret=tFO3bS5qoVHI87uw7M5Vd0jh

spring.profiles.active=manish
#redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
#logger setting
#logging.level.com.inventory.rootPackage=info
#logging.level.root=error

logging.level.org.springframework.security=DEBUG

#oauth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com

 # SMTP mail
 spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=manigapathy30@gmail.com
spring.mail.password=nybe yxzl tlvf frqe
# Use Google App Password, not your actual Gmail password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


