
 spring.application.name=inventoryManagement
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

#my sql configuration

#spring.datasource.url=jdbc:mysql://localhost:3306/inventorydb
#spring.datasource.username=root


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

#jpa configuration
spring.jpa.hibernate.ddl-auto=update


#razorpay
razorpay.key.id=rzp_test_AYfSh7nXRuJebv
razorpay.key.secret=tFO3bS5qoVHI87uw7M5Vd0jh

 spring.profiles.active=manish
 
 # SMTP mail
 spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=manigapathykc@gmail.com
spring.mail.password=woyp lpaj xnuz xyhu
# Use Google App Password, not your actual Gmail password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

