 spring.profiles.active=mani

<<<<<<< HEAD
=======
#my sql configuration
spring.datasource.url=jdbc:mysql://localhost:3306/inventorydb
spring.datasource.username=root
spring.datasource.password=nitin6127

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

#jpa configuration
spring.jpa.hibernate.ddl-auto=update
>>>>>>> c6b284929118fd06e8ac4a224c2e0c8e13af4512
